-- 02_add_ad_reward_tables.sql
-- Table for tracking LootLabs Box Roulette Transactions & Postback

CREATE TABLE IF NOT EXISTS lootlabs_box_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_user_id TEXT NOT NULL,
    guild_id TEXT,
    box_id INT NOT NULL,
    click_id TEXT NOT NULL UNIQUE,          -- puid sent to LootLabs
    lootlabs_unique_id TEXT UNIQUE,         -- unique_id received from LootLabs Postback
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'completed', 'expired'
    reward_type TEXT DEFAULT 'points',
    reward_amount INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_lootlabs_click_id ON lootlabs_box_transactions (click_id);
CREATE INDEX IF NOT EXISTS idx_lootlabs_user_id ON lootlabs_box_transactions (discord_user_id);
