-- ==============================================================================
-- SQL Migration: Standalone Questions for Game 5 (Audio EN) & Game 11 (Audio TH)
-- 100 Words per game (200 words total: Basic, Medium, Hard, Very Hard)
-- ==============================================================================

-- ── Game 5: ฟังเสียงแล้วพิมพ์ตอบ (อังกฤษ) (100 Words) ─────────────────────────
INSERT INTO public.minigame_questions (game_id, word_or_question, answer, category, difficulty, is_active) VALUES
-- Basic / Easy-Medium (25)
(5, 'apple', 'apple', 'Basic', 'easy', true),
(5, 'banana', 'banana', 'Basic', 'easy', true),
(5, 'butter', 'butter', 'Basic', 'easy', true),
(5, 'coffee', 'coffee', 'Basic', 'easy', true),
(5, 'doctor', 'doctor', 'Basic', 'easy', true),
(5, 'family', 'family', 'Basic', 'easy', true),
(5, 'garden', 'garden', 'Basic', 'easy', true),
(5, 'happy', 'happy', 'Basic', 'easy', true),
(5, 'island', 'island', 'Basic', 'easy', true),
(5, 'market', 'market', 'Basic', 'easy', true),
(5, 'morning', 'morning', 'Basic', 'easy', true),
(5, 'orange', 'orange', 'Basic', 'easy', true),
(5, 'parent', 'parent', 'Basic', 'easy', true),
(5, 'rabbit', 'rabbit', 'Basic', 'easy', true),
(5, 'school', 'school', 'Basic', 'easy', true),
(5, 'summer', 'summer', 'Basic', 'easy', true),
(5, 'teacher', 'teacher', 'Basic', 'easy', true),
(5, 'window', 'window', 'Basic', 'easy', true),
(5, 'yellow', 'yellow', 'Basic', 'easy', true),
(5, 'animal', 'animal', 'Basic', 'easy', true),
(5, 'castle', 'castle', 'Basic', 'easy', true),
(5, 'dragon', 'dragon', 'Basic', 'easy', true),
(5, 'flower', 'flower', 'Basic', 'easy', true),
(5, 'planet', 'planet', 'Basic', 'easy', true),
(5, 'silver', 'silver', 'Basic', 'easy', true),

-- Medium (25)
(5, 'adventure', 'adventure', 'Medium', 'medium', true),
(5, 'beautiful', 'beautiful', 'Medium', 'medium', true),
(5, 'chocolate', 'chocolate', 'Medium', 'medium', true),
(5, 'dangerous', 'dangerous', 'Medium', 'medium', true),
(5, 'elephant', 'elephant', 'Medium', 'medium', true),
(5, 'favorite', 'favorite', 'Medium', 'medium', true),
(5, 'hospital', 'hospital', 'Medium', 'medium', true),
(5, 'important', 'important', 'Medium', 'medium', true),
(5, 'mountain', 'mountain', 'Medium', 'medium', true),
(5, 'neighbor', 'neighbor', 'Medium', 'medium', true),
(5, 'notebook', 'notebook', 'Medium', 'medium', true),
(5, 'passenger', 'passenger', 'Medium', 'medium', true),
(5, 'sandwich', 'sandwich', 'Medium', 'medium', true),
(5, 'umbrella', 'umbrella', 'Medium', 'medium', true),
(5, 'vacation', 'vacation', 'Medium', 'medium', true),
(5, 'yesterday', 'yesterday', 'Medium', 'medium', true),
(5, 'beginner', 'beginner', 'Medium', 'medium', true),
(5, 'celebrate', 'celebrate', 'Medium', 'medium', true),
(5, 'decision', 'decision', 'Medium', 'medium', true),
(5, 'exercise', 'exercise', 'Medium', 'medium', true),
(5, 'musician', 'musician', 'Medium', 'medium', true),
(5, 'pharmacy', 'pharmacy', 'Medium', 'medium', true),
(5, 'universe', 'universe', 'Medium', 'medium', true),
(5, 'valuable', 'valuable', 'Medium', 'medium', true),
(5, 'wilderness', 'wilderness', 'Medium', 'medium', true),

-- Hard (25)
(5, 'accommodation', 'accommodation', 'Hard', 'hard', true),
(5, 'architecture', 'architecture', 'Hard', 'hard', true),
(5, 'conversation', 'conversation', 'Hard', 'hard', true),
(5, 'disappointing', 'disappointing', 'Hard', 'hard', true),
(5, 'encouragement', 'encouragement', 'Hard', 'hard', true),
(5, 'intelligence', 'intelligence', 'Hard', 'hard', true),
(5, 'performance', 'performance', 'Hard', 'hard', true),
(5, 'recommendation', 'recommendation', 'Hard', 'hard', true),
(5, 'traditional', 'traditional', 'Hard', 'hard', true),
(5, 'understanding', 'understanding', 'Hard', 'hard', true),
(5, 'characteristic', 'characteristic', 'Hard', 'hard', true),
(5, 'civilization', 'civilization', 'Hard', 'hard', true),
(5, 'demonstration', 'demonstration', 'Hard', 'hard', true),
(5, 'environment', 'environment', 'Hard', 'hard', true),
(5, 'independence', 'independence', 'Hard', 'hard', true),
(5, 'organization', 'organization', 'Hard', 'hard', true),
(5, 'qualification', 'qualification', 'Hard', 'hard', true),
(5, 'relationship', 'relationship', 'Hard', 'hard', true),
(5, 'satisfaction', 'satisfaction', 'Hard', 'hard', true),
(5, 'transportation', 'transportation', 'Hard', 'hard', true),
(5, 'enthusiastic', 'enthusiastic', 'Hard', 'hard', true),
(5, 'extraordinary', 'extraordinary', 'Hard', 'hard', true),
(5, 'investigation', 'investigation', 'Hard', 'hard', true),
(5, 'professional', 'professional', 'Hard', 'hard', true),
(5, 'sophisticated', 'sophisticated', 'Hard', 'hard', true),

-- Very Hard (25)
(5, 'incomprehensible', 'incomprehensible', 'Very Hard', 'hard', true),
(5, 'unconstitutional', 'unconstitutional', 'Very Hard', 'hard', true),
(5, 'intercontinental', 'intercontinental', 'Very Hard', 'hard', true),
(5, 'misinterpretation', 'misinterpretation', 'Very Hard', 'hard', true),
(5, 'counterproductive', 'counterproductive', 'Very Hard', 'hard', true),
(5, 'disproportionality', 'disproportionality', 'Very Hard', 'hard', true),
(5, 'electroencephalogram', 'electroencephalogram', 'Very Hard', 'hard', true),
(5, 'gastroenterology', 'gastroenterology', 'Very Hard', 'hard', true),
(5, 'hypercholesterolemia', 'hypercholesterolemia', 'Very Hard', 'hard', true),
(5, 'immunodeficiency', 'immunodeficiency', 'Very Hard', 'hard', true),
(5, 'industrialization', 'industrialization', 'Very Hard', 'hard', true),
(5, 'internationalization', 'internationalization', 'Very Hard', 'hard', true),
(5, 'micromanagement', 'micromanagement', 'Very Hard', 'hard', true),
(5, 'misunderstanding', 'misunderstanding', 'Very Hard', 'hard', true),
(5, 'multidisciplinary', 'multidisciplinary', 'Very Hard', 'hard', true),
(5, 'neurodegenerative', 'neurodegenerative', 'Very Hard', 'hard', true),
(5, 'oversimplification', 'oversimplification', 'Very Hard', 'hard', true),
(5, 'photosynthesize', 'photosynthesize', 'Very Hard', 'hard', true),
(5, 'telecommunication', 'telecommunication', 'Very Hard', 'hard', true),
(5, 'uncharacteristically', 'uncharacteristically', 'Very Hard', 'hard', true),
(5, 'uncompromisingly', 'uncompromisingly', 'Very Hard', 'hard', true),
(5, 'unidentifiable', 'unidentifiable', 'Very Hard', 'hard', true),
(5, 'unpredictable', 'unpredictable', 'Very Hard', 'hard', true),
(5, 'vulnerability', 'vulnerability', 'Very Hard', 'hard', true),
(5, 'weatherproofing', 'weatherproofing', 'Very Hard', 'hard', true);

-- ── Game 11: ฟังเสียงแล้วพิมพ์ตอบ (ไทย) (100 Words) ───────────────────────────
INSERT INTO public.minigame_questions (game_id, word_or_question, answer, category, difficulty, is_active) VALUES
-- Basic / Easy-Medium (25)
(11, 'กาแฟ', 'กาแฟ', 'พื้นฐาน', 'easy', true),
(11, 'โรงเรียน', 'โรงเรียน', 'พื้นฐาน', 'easy', true),
(11, 'ดอกไม้', 'ดอกไม้', 'พื้นฐาน', 'easy', true),
(11, 'ครอบครัว', 'ครอบครัว', 'พื้นฐาน', 'easy', true),
(11, 'สวนสัตว์', 'สวนสัตว์', 'พื้นฐาน', 'easy', true),
(11, 'กระเป๋า', 'กระเป๋า', 'พื้นฐาน', 'easy', true),
(11, 'นาฬิกา', 'นาฬิกา', 'พื้นฐาน', 'easy', true),
(11, 'รถจักรยาน', 'รถจักรยาน', 'พื้นฐาน', 'easy', true),
(11, 'สับปะรด', 'สับปะรด', 'พื้นฐาน', 'easy', true),
(11, 'ข้าวผัด', 'ข้าวผัด', 'พื้นฐาน', 'easy', true),
(11, 'มะม่วง', 'มะม่วง', 'พื้นฐาน', 'easy', true),
(11, 'ไอศกรีม', 'ไอศกรีม', 'พื้นฐาน', 'easy', true),
(11, 'ตลาดนัด', 'ตลาดนัด', 'พื้นฐาน', 'easy', true),
(11, 'โรงพยาบาล', 'โรงพยาบาล', 'พื้นฐาน', 'easy', true),
(11, 'ทะเลสาบ', 'ทะเลสาบ', 'พื้นฐาน', 'easy', true),
(11, 'ท้องฟ้า', 'ท้องฟ้า', 'พื้นฐาน', 'easy', true),
(11, 'ดวงอาทิตย์', 'ดวงอาทิตย์', 'พื้นฐาน', 'easy', true),
(11, 'วันเกิด', 'วันเกิด', 'พื้นฐาน', 'easy', true),
(11, 'ของขวัญ', 'ของขวัญ', 'พื้นฐาน', 'easy', true),
(11, 'การบ้าน', 'การบ้าน', 'พื้นฐาน', 'easy', true),
(11, 'ความสุข', 'ความสุข', 'พื้นฐาน', 'easy', true),
(11, 'ความรัก', 'ความรัก', 'พื้นฐาน', 'easy', true),
(11, 'เพื่อนสนิท', 'เพื่อนสนิท', 'พื้นฐาน', 'easy', true),
(11, 'หนังสือ', 'หนังสือ', 'พื้นฐาน', 'easy', true),
(11, 'ห้องเรียน', 'ห้องเรียน', 'พื้นฐาน', 'easy', true),

-- Medium (25)
(11, 'ประชาธิปไตย', 'ประชาธิปไตย', 'ปานกลาง', 'medium', true),
(11, 'วิทยาศาสตร์', 'วิทยาศาสตร์', 'ปานกลาง', 'medium', true),
(11, 'เทคโนโลยี', 'เทคโนโลยี', 'ปานกลาง', 'medium', true),
(11, 'สภาพแวดล้อม', 'สภาพแวดล้อม', 'ปานกลาง', 'medium', true),
(11, 'พัฒนาการ', 'พัฒนาการ', 'ปานกลาง', 'medium', true),
(11, 'วัฒนธรรม', 'วัฒนธรรม', 'ปานกลาง', 'medium', true),
(11, 'สถาปัตยกรรม', 'สถาปัตยกรรม', 'ปานกลาง', 'medium', true),
(11, 'ประสบการณ์', 'ประสบการณ์', 'ปานกลาง', 'medium', true),
(11, 'ทรัพยากร', 'ทรัพยากร', 'ปานกลาง', 'medium', true),
(11, 'อุตสาหกรรม', 'อุตสาหกรรม', 'ปานกลาง', 'medium', true),
(11, 'เอกลักษณ์', 'เอกลักษณ์', 'ปานกลาง', 'medium', true),
(11, 'ประสิทธิภาพ', 'ประสิทธิภาพ', 'ปานกลาง', 'medium', true),
(11, 'สัมพันธภาพ', 'สัมพันธภาพ', 'ปานกลาง', 'medium', true),
(11, 'พฤติกรรม', 'พฤติกรรม', 'ปานกลาง', 'medium', true),
(11, 'ปรากฏการณ์', 'ปรากฏการณ์', 'ปานกลาง', 'medium', true),
(11, 'มนุษยชาติ', 'มนุษยชาติ', 'ปานกลาง', 'medium', true),
(11, 'ภูมิศาสตร์', 'ภูมิศาสตร์', 'ปานกลาง', 'medium', true),
(11, 'ประวัติศาสตร์', 'ประวัติศาสตร์', 'ปานกลาง', 'medium', true),
(11, 'คุณค่าทางอาหาร', 'คุณค่าทางอาหาร', 'ปานกลาง', 'medium', true),
(11, 'ความรับผิดชอบ', 'ความรับผิดชอบ', 'ปานกลาง', 'medium', true),
(11, 'สุขภาพจิต', 'สุขภาพจิต', 'ปานกลาง', 'medium', true),
(11, 'การสื่อสาร', 'การสื่อสาร', 'ปานกลาง', 'medium', true),
(11, 'ภูมิปัญญา', 'ภูมิปัญญา', 'ปานกลาง', 'medium', true),
(11, 'ความหลากหลาย', 'ความหลากหลาย', 'ปานกลาง', 'medium', true),
(11, 'มลภาวะ', 'มลภาวะ', 'ปานกลาง', 'medium', true),

-- Hard (25)
(11, 'พระมหากษัตริย์', 'พระมหากษัตริย์', 'ยาก', 'hard', true),
(11, 'พระราชพิธี', 'พระราชพิธี', 'ยาก', 'hard', true),
(11, 'สุจริตชน', 'สุจริตชน', 'ยาก', 'hard', true),
(11, 'วรรณกรรมวิจารณ์', 'วรรณกรรมวิจารณ์', 'ยาก', 'hard', true),
(11, 'พุทธศาสนิกชน', 'พุทธศาสนิกชน', 'ยาก', 'hard', true),
(11, 'พระบรมราโชวาท', 'พระบรมราโชวาท', 'ยาก', 'hard', true),
(11, 'สุจริตธรรม', 'สุจริตธรรม', 'ยาก', 'hard', true),
(11, 'นัยสำคัญ', 'นัยสำคัญ', 'ยาก', 'hard', true),
(11, 'จริยธรรมองค์กร', 'จริยธรรมองค์กร', 'ยาก', 'hard', true),
(11, 'อุดมการณ์ทางการเมือง', 'อุดมการณ์ทางการเมือง', 'ยาก', 'hard', true),
(11, 'ธรรมาภิบาล', 'ธรรมาภิบาล', 'ยาก', 'hard', true),
(11, 'คุณธรรมจริยธรรม', 'คุณธรรมจริยธรรม', 'ยาก', 'hard', true),
(11, 'มนุษยสัมพันธ์', 'มนุษยสัมพันธ์', 'ยาก', 'hard', true),
(11, 'นวัตกรรมเทคโนโลยี', 'นวัตกรรมเทคโนโลยี', 'ยาก', 'hard', true),
(11, 'ปรากฏการณ์ทางธรรมชาติ', 'ปรากฏการณ์ทางธรรมชาติ', 'ยาก', 'hard', true),
(11, 'อารยธรรมโบราณ', 'อารยธรรมโบราณ', 'ยาก', 'hard', true),
(11, 'สิทธิมนุษยชน', 'สิทธิมนุษยชน', 'ยาก', 'hard', true),
(11, 'ทรัพย์สินทางปัญญา', 'ทรัพย์สินทางปัญญา', 'ยาก', 'hard', true),
(11, 'รัชทายาท', 'รัชทายาท', 'ยาก', 'hard', true),
(11, 'สัมมาชีพ', 'สัมมาชีพ', 'ยาก', 'hard', true),
(11, 'จรรยาบรรณวิชาชีพ', 'จรรยาบรรณวิชาชีพ', 'ยาก', 'hard', true),
(11, 'พระบรมมหาราชวัง', 'พระบรมมหาราชวัง', 'ยาก', 'hard', true),
(11, 'สังคมสงเคราะห์', 'สังคมสงเคราะห์', 'ยาก', 'hard', true),
(11, 'การบริหารจัดการ', 'การบริหารจัดการ', 'ยาก', 'hard', true),
(11, 'สาธารณูปโภค', 'สาธารณูปโภค', 'ยาก', 'hard', true),

-- Very Hard (25)
(11, 'พระบาทสมเด็จพระเจ้าอยู่หัว', 'พระบาทสมเด็จพระเจ้าอยู่หัว', 'ยากมาก', 'hard', true),
(11, 'พระบรมราชโองการ', 'พระบรมราชโองการ', 'ยากมาก', 'hard', true),
(11, 'พระบรมราชานุญาต', 'พระบรมราชานุญาต', 'ยากมาก', 'hard', true),
(11, 'อรรถกถาจารย์', 'อรรถกถาจารย์', 'ยากมาก', 'hard', true),
(11, 'พุทธานุภาพ', 'พุทธานุภาพ', 'ยากมาก', 'hard', true),
(11, 'สังฆานุภาพ', 'สังฆานุภาพ', 'ยากมาก', 'hard', true),
(11, 'พระธรรมาภิบาล', 'พระธรรมาภิบาล', 'ยากมาก', 'hard', true),
(11, 'พระเศวตฉัตร', 'พระเศวตฉัตร', 'ยากมาก', 'hard', true),
(11, 'พระสุพรรณบัฏ', 'พระสุพรรณบัฏ', 'ยากมาก', 'hard', true),
(11, 'พระอารามหลวง', 'พระอารามหลวง', 'ยากมาก', 'hard', true),
(11, 'พระสังฆราชสกลมหาสังฆปริณายก', 'พระสังฆราชสกลมหาสังฆปริณายก', 'ยากมาก', 'hard', true),
(11, 'อริยสัจสี่', 'อริยสัจสี่', 'ยากมาก', 'hard', true),
(11, 'มงคลสูตร', 'มงคลสูตร', 'ยากมาก', 'hard', true),
(11, 'ปฏิจจสมุปบาท', 'ปฏิจจสมุปบาท', 'ยากมาก', 'hard', true),
(11, 'วิปัสสนากรรมฐาน', 'วิปัสสนากรรมฐาน', 'ยากมาก', 'hard', true),
(11, 'พระนิพพาน', 'พระนิพพาน', 'ยากมาก', 'hard', true),
(11, 'พระไตรปิฎก', 'พระไตรปิฎก', 'ยากมาก', 'hard', true),
(11, 'กุศโลบาย', 'กุศโลบาย', 'ยากมาก', 'hard', true),
(11, 'พระราชบัณฑิตยสภา', 'พระราชบัณฑิตยสภา', 'ยากมาก', 'hard', true),
(11, 'ศิลปวัฒนธรรมประเพณี', 'ศิลปวัฒนธรรมประเพณี', 'ยากมาก', 'hard', true),
(11, 'สัมมาทิฐิ', 'สัมมาทิฐิ', 'ยากมาก', 'hard', true),
(11, 'ปริยัติธรรม', 'ปริยัติธรรม', 'ยากมาก', 'hard', true),
(11, 'สังฆทาน', 'สังฆทาน', 'ยากมาก', 'hard', true),
(11, 'สุจริตวิถี', 'สุจริตวิถี', 'ยากมาก', 'hard', true),
(11, 'พระบรมอัฐิ', 'พระบรมอัฐิ', 'ยากมาก', 'hard', true);
