-- sql/heal_jai_tickets.sql
-- ตารางเก็บข้อมูลการเปิดใช้งาน Ticket / เลือกเมนูในระบบ HealJai

CREATE TABLE IF NOT EXISTS heal_jai_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id TEXT NOT NULL,
  channel_id TEXT NOT NULL UNIQUE,
  user_id TEXT NOT NULL,
  notice_message_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'accepted', 'cancelled', 'expired'
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index สำหรับค้นหาตั๋วตาม User และ Status
CREATE INDEX IF NOT EXISTS idx_heal_jai_tickets_user_status ON heal_jai_tickets(user_id, status);
CREATE INDEX IF NOT EXISTS idx_heal_jai_tickets_guild_status ON heal_jai_tickets(guild_id, status);

-- Row Level Security (RLS) Policies
ALTER TABLE heal_jai_tickets ENABLE ROW LEVEL SECURITY;

-- อนุญาตให้ Service Role จัดการข้อมูลได้สมบูรณ์
CREATE POLICY "Enable all for service role" ON heal_jai_tickets
  FOR ALL
  USING (true)
  WITH CHECK (true);
