-- sql/heal_jai_core_system.sql
-- โครงสร้างฐานข้อมูลหลักของระบบ Bear Cafe ฮีลใจ (Counselors, Orders/Sessions, Reviews, Payouts)

-- 1. ตารางเก็บข้อมูลผู้ให้คำปรึกษา (Counselors & Baristas)
CREATE TABLE IF NOT EXISTS heal_jai_counselors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id TEXT NOT NULL,
  user_id TEXT NOT NULL UNIQUE,
  display_name TEXT,
  status TEXT NOT NULL DEFAULT 'OFFLINE' CHECK (status IN ('ONLINE', 'BUSY', 'BREAK', 'OFFLINE')),
  specialty_tags TEXT[] DEFAULT '{}',
  is_silent_companion BOOLEAN DEFAULT false,
  total_sessions INTEGER DEFAULT 0,
  average_rating NUMERIC(3,2) DEFAULT 5.00,
  total_reviews INTEGER DEFAULT 0,
  accumulated_earnings NUMERIC(10,2) DEFAULT 0.00,
  payout_account TEXT,
  last_shift_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_heal_jai_counselors_status ON heal_jai_counselors(guild_id, status);
CREATE INDEX IF NOT EXISTS idx_heal_jai_counselors_user ON heal_jai_counselors(user_id);

ALTER TABLE heal_jai_counselors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for service role on heal_jai_counselors" ON heal_jai_counselors
  FOR ALL USING (true) WITH CHECK (true);

-- 2. ตารางเก็บออเดอร์และเซสชันการให้บริการ (Orders & Sessions)
CREATE TABLE IF NOT EXISTS heal_jai_orders_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_code TEXT NOT NULL UNIQUE,
  guild_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  counselor_id TEXT,
  package_tier TEXT NOT NULL CHECK (package_tier IN ('S', 'M', 'L')),
  package_name TEXT, -- เช่น 'ชาเขียวอุ่นใจ', 'โกโก้พักใจ', 'กาแฟคุยยาว'
  duration_minutes INTEGER NOT NULL,
  is_silent BOOLEAN DEFAULT false,
  is_specific_counselor BOOLEAN DEFAULT false,
  is_booster BOOLEAN DEFAULT false,
  grace_period_minutes INTEGER DEFAULT 0,
  total_price NUMERIC(10,2) NOT NULL,
  counselor_share NUMERIC(10,2) NOT NULL, -- 70%
  platform_share NUMERIC(10,2) NOT NULL,  -- 30%
  payment_status TEXT NOT NULL DEFAULT 'PENDING' CHECK (payment_status IN ('PENDING', 'PAID', 'REFUNDED', 'CANCELLED')),
  session_status TEXT NOT NULL DEFAULT 'WAITING' CHECK (session_status IN ('WAITING', 'DISPATCHING', 'ACTIVE', 'COMPLETED', 'CANCELLED')),
  ticket_channel_id TEXT,
  session_channel_id TEXT,
  session_voice_id TEXT,
  slip_url TEXT,
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_heal_jai_orders_status ON heal_jai_orders_sessions(guild_id, session_status);
CREATE INDEX IF NOT EXISTS idx_heal_jai_orders_customer ON heal_jai_orders_sessions(customer_id);
CREATE INDEX IF NOT EXISTS idx_heal_jai_orders_counselor ON heal_jai_orders_sessions(counselor_id);

ALTER TABLE heal_jai_orders_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for service role on heal_jai_orders_sessions" ON heal_jai_orders_sessions
  FOR ALL USING (true) WITH CHECK (true);

-- 3. ตารางเก็บบันทึกรีวิวและความประทับใจ (Reviews & Ratings)
CREATE TABLE IF NOT EXISTS heal_jai_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id TEXT NOT NULL,
  order_id BIGINT REFERENCES heal_jai_orders_sessions(id) ON DELETE SET NULL,
  customer_id TEXT NOT NULL,
  counselor_id TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  is_anonymous BOOLEAN DEFAULT true,
  public_message_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_heal_jai_reviews_counselor ON heal_jai_reviews(counselor_id);
CREATE INDEX IF NOT EXISTS idx_heal_jai_reviews_guild ON heal_jai_reviews(guild_id);

ALTER TABLE heal_jai_reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for service role on heal_jai_reviews" ON heal_jai_reviews
  FOR ALL USING (true) WITH CHECK (true);

-- 4. ตารางบันทึกการตัดรอบโอนเงิน (Payouts)
CREATE TABLE IF NOT EXISTS heal_jai_payouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id TEXT NOT NULL,
  counselor_id TEXT NOT NULL,
  amount NUMERIC(10,2) NOT NULL,
  period_end DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PAID', 'CANCELLED')),
  payout_account TEXT,
  paid_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_heal_jai_payouts_counselor ON heal_jai_payouts(counselor_id);

ALTER TABLE heal_jai_payouts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for service role on heal_jai_payouts" ON heal_jai_payouts
  FOR ALL USING (true) WITH CHECK (true);
