-- sql/heal_jai_consents.sql
-- ตารางเก็บความยินยอมของผู้ใช้งานในการยอมรับข้อตกลงและเงื่อนไขการให้บริการ (HealJai Consent Tracking)

CREATE TABLE IF NOT EXISTS heal_jai_consents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  version TEXT NOT NULL DEFAULT 'v1.0',
  consent_type TEXT NOT NULL DEFAULT 'agreement',
  role_assigned BOOLEAN DEFAULT true,
  accepted_at TIMESTAMPTZ DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes สำหรับการค้นหาความยินยอมตาม User ID และ Guild ID
CREATE INDEX IF NOT EXISTS idx_heal_jai_consents_user_ver ON heal_jai_consents(user_id, version);
CREATE INDEX IF NOT EXISTS idx_heal_jai_consents_guild ON heal_jai_consents(guild_id);

-- เปิดใช้งาน Row Level Security (RLS)
ALTER TABLE heal_jai_consents ENABLE ROW LEVEL SECURITY;

-- นโยบาย RLS สำหรับ Service Role ของบอท
CREATE POLICY "Enable all for service role on heal_jai_consents" ON heal_jai_consents
  FOR ALL
  USING (true)
  WITH CHECK (true);
