-- ==============================================================================
-- BEAR CAFE BOT: MINI-GAMES & USER POINTS DAILY CAP SYSTEM (CONSOLIDATED SQL)
-- ==============================================================================

-- 1. เพิ่มคอลัมน์ระบบโควต้าแต้มประจำวันในตาราง user_points
ALTER TABLE user_points 
ADD COLUMN IF NOT EXISTS max_cap INT DEFAULT 750,
ADD COLUMN IF NOT EXISTS daily_points INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_reset_date TEXT DEFAULT '';

-- 2. ตารางคลังโจทย์ / คำศัพท์ / คำใบ้ / ตัวเลือก (สำหรับ Admin Dashboard จัดการ CRUD)
CREATE TABLE IF NOT EXISTS minigame_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id INT NOT NULL,               -- หมายเลขเกม (1-10)
    word_or_question TEXT NOT NULL,      -- โจทย์ / คำศัพท์หลัก
    answer TEXT NOT NULL,                -- คำตอบ / เฉลยที่ถูกต้อง
    hints JSONB DEFAULT '[]'::jsonb,     -- คำใบ้ 1, 2, 3 (เฉพาะเกมที่ 4)
    options JSONB DEFAULT '[]'::jsonb,   -- ตัวเลือกช้อยส์ (เฉพาะเกมที่ 9 และ 10)
    difficulty TEXT DEFAULT NULL,        -- ระดับความยาก: 'easy', 'medium', 'hard' (มีเฉพาะเกม 3 และ 4, เกมอื่นเป็น NULL)
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_minigame_questions_game ON minigame_questions (game_id, is_active);

-- 3. ตารางตั้งค่ามินิเกม (จัดการ Channel ID และการเปิด/ปิด ผ่าน Admin Dashboard)
CREATE TABLE IF NOT EXISTS minigame_settings (
    game_id INT PRIMARY KEY,
    game_name TEXT NOT NULL,
    channel_id TEXT NOT NULL,
    is_enabled BOOLEAN DEFAULT true,
    min_points INT DEFAULT 3,
    max_points INT DEFAULT 6,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- บันทึกข้อมูลเริ่มต้นของมินิเกมทั้ง 10 เกม
INSERT INTO minigame_settings (game_id, game_name, channel_id, min_points, max_points) VALUES
(1, 'เติมคำศัพท์ไทย', '1534437994327572510', 3, 6),
(2, 'เติมคำศัพท์ภาษาอังกฤษ', '1534453700188176506', 3, 6),
(3, 'สุ่มโจทย์คณิตฯ', '1534454001532272730', 2, 10),
(4, 'ทายคำจากคำใบ้', '1534458749782200390', 2, 10),
(5, 'เรียงคำศัพท์ไทย', '1534459076606431272', 3, 6),
(6, 'เรียงคำศัพท์อังกฤษ', '1534459381779795998', 3, 6),
(7, 'พิมพ์คำต่อไปนี้ (ไทย)', '1534469630234726431', 3, 6),
(8, 'พิมพ์คำต่อไปนี้ (อังกฤษ)', '1534469708517085315', 3, 6),
(9, 'ทายคำแปลภาษาอังกฤษ', '1534647461262393435', 3, 6),
(10, 'ทายคำแปลภาษาไทย', '1534647589121818795', 3, 6)
ON CONFLICT (game_id) DO UPDATE SET 
    channel_id = EXCLUDED.channel_id,
    game_name = EXCLUDED.game_name;

-- 4. ตารางบันทึกการชนะมินิเกมของผู้ใช้ (สำหรับจัดอันดับ Leaderboard แบบ 30 วัน และ แบบทั้งหมด)
CREATE TABLE IF NOT EXISTS minigame_wins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id TEXT NOT NULL,
    game_id INT NOT NULL,
    points_earned INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_minigame_wins_leaderboard ON minigame_wins (discord_id, created_at);
CREATE INDEX IF NOT EXISTS idx_minigame_wins_game ON minigame_wins (game_id);

-- 5. ตารางเก็บสถานะโจทย์ปัจจุบันประจำแต่ละห้อง
CREATE TABLE IF NOT EXISTS minigame_active_sessions (
    channel_id TEXT PRIMARY KEY,
    game_id INT NOT NULL,
    current_question JSONB NOT NULL,
    message_id TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==============================================================================
-- 🔓 ROW LEVEL SECURITY (RLS) PERMISSIONS FOR WEB APP ACCESS
-- ==============================================================================
-- ปิด RLS หรืออนุญาตให้สิทธิ์ Anon/Authenticated อ่านเขียนตารางมินิเกมผ่านหน้าเว็บได้
ALTER TABLE minigame_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE minigame_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE minigame_wins DISABLE ROW LEVEL SECURITY;
ALTER TABLE minigame_active_sessions DISABLE ROW LEVEL SECURITY;

GRANT ALL ON minigame_questions TO anon, authenticated, service_role;
GRANT ALL ON minigame_settings TO anon, authenticated, service_role;
GRANT ALL ON minigame_wins TO anon, authenticated, service_role;
GRANT ALL ON minigame_active_sessions TO anon, authenticated, service_role;

-- ตัวอย่างข้อมูลโจทย์เริ่มต้นเข้าคลังมินิเกม (difficulty เป็น NULL สำหรับเกมที่ไม่มีระดับความยาก)
INSERT INTO minigame_questions (game_id, word_or_question, answer, hints, options, difficulty) VALUES
-- Game 1: เติมคำศัพท์ไทย (ไม่มีระดับความยาก)
(1, 'สวัสดี', 'สวัสดี', '[]'::jsonb, '[]'::jsonb, NULL),
(1, 'ขอบคุณ', 'ขอบคุณ', '[]'::jsonb, '[]'::jsonb, NULL),
(1, 'ประเทศไทย', 'ประเทศไทย', '[]'::jsonb, '[]'::jsonb, NULL),
(1, 'มิตรภาพ', 'มิตรภาพ', '[]'::jsonb, '[]'::jsonb, NULL),
(1, 'ความสุข', 'ความสุข', '[]'::jsonb, '[]'::jsonb, NULL),

-- Game 2: เติมคำศัพท์ภาษาอังกฤษ (ไม่มีระดับความยาก)
(2, 'apple', 'apple', '[]'::jsonb, '[]'::jsonb, NULL),
(2, 'banana', 'banana', '[]'::jsonb, '[]'::jsonb, NULL),
(2, 'friendship', 'friendship', '[]'::jsonb, '[]'::jsonb, NULL),
(2, 'welcome', 'welcome', '[]'::jsonb, '[]'::jsonb, NULL),
(2, 'sunshine', 'sunshine', '[]'::jsonb, '[]'::jsonb, NULL),

-- Game 4: ทายคำจากคำใบ้ (มีระดับความยาก: easy, medium, hard)
(4, 'สุนัข', 'สุนัข', '["เป็นสัตว์สี่ขา", "ส่งเสียงร้องโฮ่งๆ", "เพื่อนที่ซื่อสัตย์ของมนุษย์"]'::jsonb, '[]'::jsonb, 'easy'),
(4, 'แมว', 'แมว', '["เป็นสัตว์เลี้ยงยอดนิยม", "ส่งเสียงร้องเหมียวๆ", "ชอบนอนและจับหนู"]'::jsonb, '[]'::jsonb, 'easy'),
(4, 'ช้าง', 'ช้าง', '["เป็นสัตว์คู่บ้านคู่เมืองไทย", "ตัวใหญ่ มีงวง มีงา", "ชอบกินอ้อยและกล้วย"]'::jsonb, '[]'::jsonb, 'medium'),
(4, 'ดวงอาทิตย์', 'ดวงอาทิตย์', '["อยู่บนท้องฟ้า", "ให้แสงสว่างและความร้อนในตอนกลางวัน", "ขึ้นทางทิศตะวันออก"]'::jsonb, '[]'::jsonb, 'medium'),
(4, 'คอมพิวเตอร์', 'คอมพิวเตอร์', '["เป็นอุปกรณ์อิเล็กทรอนิกส์", "มีหน้าจอ แป้นพิมพ์ และเมาส์", "ใช้ประมวลผลและทำงาน"]'::jsonb, '[]'::jsonb, 'hard'),

-- Game 5: เรียงคำศัพท์ไทย (ไม่มีระดับความยาก)
(5, 'สวัสดี', 'สวัสดี', '[]'::jsonb, '[]'::jsonb, NULL),
(5, 'กาแฟ', 'กาแฟ', '[]'::jsonb, '[]'::jsonb, NULL),
(5, 'ความรัก', 'ความรัก', '[]'::jsonb, '[]'::jsonb, NULL),
(5, 'ธรรมชาติ', 'ธรรมชาติ', '[]'::jsonb, '[]'::jsonb, NULL),

-- Game 6: เรียงคำศัพท์อังกฤษ (ไม่มีระดับความยาก)
(6, 'coffee', 'coffee', '[]'::jsonb, '[]'::jsonb, NULL),
(6, 'discord', 'discord', '[]'::jsonb, '[]'::jsonb, NULL),
(6, 'butterfly', 'butterfly', '[]'::jsonb, '[]'::jsonb, NULL),
(6, 'rainbow', 'rainbow', '[]'::jsonb, '[]'::jsonb, NULL),

-- Game 7: พิมพ์คำต่อไปนี้ (ไทย) (ไม่มีระดับความยาก)
(7, 'หมีคาเฟ่ต้อนรับเสมอ', 'หมีคาเฟ่ต้อนรับเสมอ', '[]'::jsonb, '[]'::jsonb, NULL),
(7, 'ยิ้มสดใสในทุกวัน', 'ยิ้มสดใสในทุกวัน', '[]'::jsonb, '[]'::jsonb, NULL),
(7, 'กาแฟหอมหวานกลมกล่อม', 'กาแฟหอมหวานกลมกล่อม', '[]'::jsonb, '[]'::jsonb, NULL),

-- Game 8: พิมพ์คำต่อไปนี้ (อังกฤษ) (ไม่มีระดับความยาก)
(8, 'Welcome to Bear Cafe', 'Welcome to Bear Cafe', '[]'::jsonb, '[]'::jsonb, NULL),
(8, 'Have a wonderful day', 'Have a wonderful day', '[]'::jsonb, '[]'::jsonb, NULL),
(8, 'Stay happy and positive', 'Stay happy and positive', '[]'::jsonb, '[]'::jsonb, NULL),

-- Game 9: ทายคำแปลภาษาอังกฤษ (ไม่มีระดับความยาก)
(9, 'Banana', 'กล้วย', '[]'::jsonb, '["กล้วย", "แอปเปิ้ล", "องุ่น"]'::jsonb, NULL),
(9, 'Apple', 'แอปเปิ้ล', '[]'::jsonb, '["แอปเปิ้ล", "ส้ม", "มะม่วง"]'::jsonb, NULL),
(9, 'Cat', 'แมว', '[]'::jsonb, '["แมว", "สุนัข", "กระต่าย"]'::jsonb, NULL),
(9, 'Book', 'หนังสือ', '[]'::jsonb, '["หนังสือ", "ปากกา", "สมุด"]'::jsonb, NULL),

-- Game 10: ทายคำแปลภาษาไทย (ไม่มีระดับความยาก)
(10, 'ส้ม', 'Orange', '[]'::jsonb, '["Orange", "Apple", "Grape"]'::jsonb, NULL),
(10, 'สุนัข', 'Dog', '[]'::jsonb, '["Dog", "Cat", "Bird"]'::jsonb, NULL),
(10, 'บ้าน', 'House', '[]'::jsonb, '["House", "Car", "School"]'::jsonb, NULL),
(10, 'น้ำ', 'Water', '[]'::jsonb, '["Water", "Milk", "Juice"]'::jsonb, NULL)
ON CONFLICT DO NOTHING;
